import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabaseQuery } from '@/lib/supabaseQuery';
import { useAuth } from '@/contexts/AuthContext';
import { toast } from 'sonner';
import { useTransferAutomation } from '@/hooks/useTransferAutomation';
import type { TransferRequest, TransferRequestStatus, TransferFilters, TransferDocument, TransferItem } from '@/types/transfers';

export function useTransferRequests(filters?: Partial<TransferFilters>) {
  const { profile } = useAuth();
  const queryClient = useQueryClient();
  const { onTransferCreated, onTransferStatusChanged } = useTransferAutomation();

  const { data: requests = [], isLoading, error, refetch } = useQuery({
    queryKey: ['transfer-requests', profile?.organization_id, filters],
    queryFn: async (): Promise<TransferRequest[]> => {
      if (!profile?.organization_id) return [];

      let query = supabaseQuery
        .from('transfer_requests')
        .select(`
          *,
          items:transfer_items(id, transfer_date, status, price_with_commission)
        `)
        .eq('organization_id', profile.organization_id);

      // Apply filters
      if (filters?.status && filters.status !== 'all') {
        query = query.eq('status', filters.status);
      }

      if (filters?.broker) {
        query = query.ilike('broker_name', `%${filters.broker}%`);
      }
      if (filters?.search) {
        query = query.or(`broker_name.ilike.%${filters.search}%,client_name.ilike.%${filters.search}%,request_number.ilike.%${filters.search}%`);
      }

      if (filters?.serviceType && filters.serviceType !== 'all') {
        query = query.eq('service_type', filters.serviceType);
      }

      // Filter archived: by default hide archived, show only when toggle is on
      if (!filters?.showArchived) {
        query = query.is('archived_at', null);
      }

      const { data, error } = await query;

      if (error) {
        console.error('Error fetching transfer requests:', error);
        throw error;
      }

      // Process data to add computed fields
      const processed = (data || []).map((request: any) => {
        const items = request.items || [];
        const dates = items.map((i: { transfer_date: string | null }) => i.transfer_date).filter(Boolean).sort();
        const total_amount = items.reduce((sum: number, i: { price_with_commission: number | null }) => 
          sum + (i.price_with_commission || 0), 0);
        return {
          ...request,
          status: request.status as TransferRequestStatus,
          items_count: items.length,
          first_transfer_date: dates[0] || null,
          total_amount,
        };
      }) as TransferRequest[];

      // Filter by date range (based on first_transfer_date from items)
      let filtered = processed;
      if (filters?.dateFrom) {
        filtered = filtered.filter(r => {
          if (!r.first_transfer_date) return false;
          return r.first_transfer_date >= filters.dateFrom!;
        });
      }
      if (filters?.dateTo) {
        filtered = filtered.filter(r => {
          if (!r.first_transfer_date) return false;
          return r.first_transfer_date <= filters.dateTo!;
        });
      }

      // Sort by first_transfer_date (requests without date go to the end)
      return filtered.sort((a, b) => {
        if (!a.first_transfer_date && !b.first_transfer_date) return 0;
        if (!a.first_transfer_date) return 1;
        if (!b.first_transfer_date) return -1;
        return new Date(a.first_transfer_date).getTime() - new Date(b.first_transfer_date).getTime();
      });
    },
    enabled: !!profile?.organization_id,
  });

  const createRequest = useMutation({
    mutationFn: async (data: Partial<TransferRequest>) => {
      if (!profile?.organization_id) throw new Error('No organization');

      const { data: result, error } = await supabaseQuery
        .from('transfer_requests')
        .insert([{
          organization_id: profile.organization_id,
          request_number: '', // Will be auto-generated by trigger
          broker_name: data.broker_name!,
          broker_id: data.broker_id || null,
          client_name: data.client_name!,
          is_external_provider: data.is_external_provider ?? false,
          external_provider_name: data.external_provider_name,
          notes: data.notes,
          created_by: profile.id,
        }])
        .select()
        .single();

      if (error) throw error;
      return result;
    },
    onSuccess: (result: any, variables: Partial<TransferRequest>) => {
      queryClient.invalidateQueries({ queryKey: ['transfer-requests'] });
      toast.success('Solicitud de transfer creada');
      // Fire automation for transfer_created
      if (result?.id) {
        onTransferCreated({
          request_id: result.id,
          status: 'pendiente',
          broker_id: variables.broker_id,
          broker_name: variables.broker_name,
          client_name: variables.client_name,
          request_number: result.request_number,
        });
      }
    },
    onError: (error: Error) => {
      toast.error(`Error al crear solicitud: ${error.message}`);
    },
  });

  const updateRequest = useMutation({
    mutationFn: async ({ id, ...data }: Partial<TransferRequest> & { id: string }) => {
      const { error } = await supabaseQuery
        .from('transfer_requests')
        .update(data)
        .eq('id', id);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['transfer-requests'] });
      toast.success('Solicitud actualizada');
    },
    onError: (error: Error) => {
      toast.error(`Error al actualizar: ${error.message}`);
    },
  });

  const updateStatus = useMutation({
    mutationFn: async ({ id, status, previousStatus, brokerId, brokerName, clientName, requestNumber }: {
      id: string;
      status: TransferRequestStatus;
      previousStatus?: string;
      brokerId?: string | null;
      brokerName?: string;
      clientName?: string;
      requestNumber?: string;
    }) => {
      const { error } = await supabaseQuery
        .from('transfer_requests')
        .update({ status })
        .eq('id', id);

      if (error) throw error;
      return { id, status, previousStatus, brokerId, brokerName, clientName, requestNumber };
    },
    onSuccess: (result) => {
      queryClient.invalidateQueries({ queryKey: ['transfer-requests'] });
      queryClient.invalidateQueries({ queryKey: ['transfer-request'] });
      toast.success('Estado actualizado');
      // Fire automation for transfer_status_changed
      if (result) {
        onTransferStatusChanged({
          request_id: result.id,
          status: result.status,
          previous_status: result.previousStatus,
          broker_id: result.brokerId,
          broker_name: result.brokerName,
          client_name: result.clientName,
          request_number: result.requestNumber,
        });
      }
    },
    onError: (error: Error) => {
      toast.error(`Error al cambiar estado: ${error.message}`);
    },
  });

  const archiveRequest = useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabaseQuery
        .from('transfer_requests')
        .update({ archived_at: new Date().toISOString() })
        .eq('id', id);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['transfer-requests'] });
      toast.success('Solicitud archivada');
    },
    onError: (error: Error) => {
      toast.error(`Error al archivar: ${error.message}`);
    },
  });

  const unarchiveRequest = useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabaseQuery
        .from('transfer_requests')
        .update({ archived_at: null })
        .eq('id', id);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['transfer-requests'] });
      toast.success('Solicitud desarchivada');
    },
    onError: (error: Error) => {
      toast.error(`Error al desarchivar: ${error.message}`);
    },
  });

  const deleteRequest = useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabaseQuery
        .from('transfer_requests')
        .delete()
        .eq('id', id);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['transfer-requests'] });
      toast.success('Solicitud eliminada');
    },
    onError: (error: Error) => {
      toast.error(`Error al eliminar: ${error.message}`);
    },
  });

  return {
    requests,
    isLoading,
    error,
    refetch,
    createRequest: createRequest.mutateAsync,
    updateRequest: updateRequest.mutate,
    updateStatus: updateStatus.mutate,
    archiveRequest: archiveRequest.mutate,
    unarchiveRequest: unarchiveRequest.mutate,
    deleteRequest: deleteRequest.mutate,
    isCreating: createRequest.isPending,
    isUpdating: updateRequest.isPending,
  };
}

export function useTransferRequest(id: string | undefined) {
  const { profile } = useAuth();

  const query = useQuery({
    queryKey: ['transfer-request', id],
    queryFn: async (): Promise<TransferRequest | null> => {
      if (!id) return null;

      const { data, error } = await supabaseQuery
        .from('transfer_requests')
        .select(`
          *,
          items:transfer_items(*),
          documents:transfer_documents(*)
        `)
        .eq('id', id)
        .single();

      if (error) {
        console.error('Error fetching transfer request:', error);
        throw error;
      }

      // Map documents to correct types (JSON fields from DB need casting)
      const documents = (data.documents || []).map((doc: unknown) => doc as TransferDocument);
      const items = (data.items || []).map((item: unknown) => item as TransferItem);

      return {
        ...data,
        status: data.status as TransferRequestStatus,
        documents,
        items,
      } as TransferRequest;
    },
    enabled: !!id && !!profile?.organization_id,
    // Poll every 3 seconds when any document is being processed by AI
    refetchInterval: (query) => {
      const request = query.state.data;
      if (!request) return false;
      const hasProcessing = request.documents?.some(
        (d: TransferDocument) => d.ai_status === 'pending' || d.ai_status === 'processing'
      );
      return hasProcessing ? 3000 : false;
    },
  });

  return query;
}
