import { describe, it, expect } from "vitest";
import { createHash } from "crypto";

/**
 * Test the token hashing logic used by signupWithInvitation.
 * The DB function uses: encode(sha256(token::bytea), 'hex')
 * Our Node.js implementation must produce the same hash.
 */
function hashToken(token: string): string {
  return createHash("sha256").update(Buffer.from(token, "utf-8")).digest("hex");
}

describe("signupWithInvitation", () => {
  describe("hashToken", () => {
    it("should produce a valid SHA256 hex hash", () => {
      const token = "abc123test";
      const hash = hashToken(token);
      // SHA256 hex output is always 64 characters
      expect(hash).toHaveLength(64);
      // Should be lowercase hex
      expect(hash).toMatch(/^[0-9a-f]{64}$/);
    });

    it("should produce consistent hashes for the same input", () => {
      const token = "test-invitation-token-xyz";
      const hash1 = hashToken(token);
      const hash2 = hashToken(token);
      expect(hash1).toBe(hash2);
    });

    it("should produce different hashes for different inputs", () => {
      const hash1 = hashToken("token-a");
      const hash2 = hashToken("token-b");
      expect(hash1).not.toBe(hash2);
    });

    it("should match the PostgreSQL sha256 output for known values", () => {
      // PostgreSQL: encode(sha256('hello'::bytea), 'hex')
      // = 2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824
      const hash = hashToken("hello");
      expect(hash).toBe("2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824");
    });

    it("should handle empty string", () => {
      const hash = hashToken("");
      // SHA256 of empty string
      expect(hash).toBe("e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855");
    });

    it("should handle hex-encoded tokens (like those generated by gen_random_bytes)", () => {
      // The create_invitation_secure function generates tokens as:
      // encode(extensions.gen_random_bytes(32), 'hex')
      // which produces a 64-char hex string
      const token = "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2";
      const hash = hashToken(token);
      expect(hash).toHaveLength(64);
      expect(hash).toMatch(/^[0-9a-f]{64}$/);
    });
  });

  describe("request validation", () => {
    it("should identify missing fields correctly", () => {
      const bodies = [
        { email: "test@test.com", password: "123456", name: "Test" }, // missing token
        { email: "test@test.com", password: "123456", token: "abc" }, // missing name
        { email: "test@test.com", name: "Test", token: "abc" }, // missing password
        { password: "123456", name: "Test", token: "abc" }, // missing email
      ];

      for (const body of bodies) {
        const { email, password, name, token } = body as any;
        const hasMissing = !email || !password || !name || !token;
        expect(hasMissing).toBe(true);
      }
    });

    it("should pass validation with all fields present", () => {
      const body = { email: "test@test.com", password: "123456", name: "Test User", token: "abc123" };
      const { email, password, name, token } = body;
      const hasMissing = !email || !password || !name || !token;
      expect(hasMissing).toBe(false);
    });
  });

  describe("email matching", () => {
    it("should match emails case-insensitively", () => {
      const invitationEmail = "Test@Example.COM";
      const inputEmail = "  test@example.com  ";
      const matches = invitationEmail.toLowerCase() === inputEmail.trim().toLowerCase();
      expect(matches).toBe(true);
    });

    it("should reject mismatched emails", () => {
      const invitationEmail = "invited@example.com";
      const inputEmail = "other@example.com";
      const matches = invitationEmail.toLowerCase() === inputEmail.trim().toLowerCase();
      expect(matches).toBe(false);
    });
  });
});
