const normalize = (value: string) => value.normalize('NFKD').replace(/[\u0300-\u036f]/g, '')
  .toUpperCase().replace(/[^A-Z0-9]+/g, '_').replace(/^_+|_+$/g, '');

export const SES_VEHICLE_BRANDS = new Set([
  'ABARTH','ACROSS','ADRIA','AIWAYS','ALFA_ROMEO','ALPINE','APRILIA','ASTON_MART','AUDI','AUTOSTAR',
  'BENIMAR','BENTLEY','BLUCAMP','BMW','BUNKERVAN','BURSTNER','CADILLAC','CAMPER','CARADO','CARAVELAIR',
  'CARTHAGO','CATERHAM','CHALLENGER','CHEVROLET','CITROEN','CLEVERVANS','CONCORDE','CUPRA','DACIA',
  'DETHLEFFS','DR','DREAMER','DS','DUCATI','ELNAGH','ERIBA','ETRUSCO','FANTIC','FENDT','FERRARI','FIAT',
  'FLEURETTE','FORD','FRANKIA','FURGOKARAV','GIOTTILINE','HARLEY','HOBBY','HONDA','HYMER','HYUNDAI',
  'ILUSION','INFINITY','ISUZU','ITINEO','IVECO','JAECOO','JAGUAR','JEEP','JOA_CAMP','KAWASAKI','KIA',
  'KNAUS','KTM','KYMKO','LADA','LAIKA','LAMBORGHIN','LANCIA','LAND_ROVER','LEVOYAGEUR','LEXUS','LOTUS',
  'LYNCCO','MACBOR','MADEMOTO','MALIBU','MASERATI','MAXUS','MAZDA','MCLOUIS','MERCEDES','MG','MINI',
  'MITSUBISHI','MOBILVETTA','MOOVEO','MORELO','MORGAN','MORINI','NISSAN','NORANTZ','OMODA','OPEL',
  'PANAMA','PEUGEOT','PHOENIX','PIAGGIO','PILOTE','POLESTAR','PORSCHE','POSSL','QJMOTOR','RANGEROVER',
  'RAPIDO','RENAULT','RIMOR','ROLLERTEAM','ROLLS_ROYC','SAAB','SEAT','SERES','SILENCE','SILVER','SKODA',
  'SMART','SSANGYONG','STERCKEMAN','SUBARU','SUNLIGHT','SUN_LIVING','SUZUKI','SYM','TABBERT','TATA',
  'TESLA','TOYOTA','TRIUMPH','VOGE','VOLKSWAGEN','VOLVO','WEINSBERG','WESTALIA','YAMAHA','OTRO',
]);

export const SES_VEHICLE_COLORS = new Set([
  'AMARILLO','AZUL','BEIGE','BLANCO','CIAN','GRANATE','GRIS','LILA','MARINO','MARRON','MOSTAZA',
  'NARANJA','NEGRO','OLIVA','PLATA','PURPURA','ROJO','ROSA','SALMON','TURQUESA','VERDE','OTRO',
]);

const BRAND_ALIASES: Record<string, string> = {
  MERCEDES_BENZ: 'MERCEDES', MERCEDESBENZ: 'MERCEDES', LANDROVER: 'LAND_ROVER',
  RANGE_ROVER: 'RANGEROVER', ALFA_ROMEO_AUTOMOBILES: 'ALFA_ROMEO',
  CITROEN: 'CITROEN', ROLLS_ROYCE: 'ROLLS_ROYC', ASTON_MARTIN: 'ASTON_MART',
  LAMBORGHINI: 'LAMBORGHIN', INFINITI: 'INFINITY',
};

const COLOR_ALIASES: Record<string, string> = {
  WHITE: 'BLANCO', BLACK: 'NEGRO', GREY: 'GRIS', GRAY: 'GRIS', SILVER: 'PLATA', BLUE: 'AZUL',
  NAVY: 'MARINO', RED: 'ROJO', GREEN: 'VERDE', YELLOW: 'AMARILLO', ORANGE: 'NARANJA',
  BROWN: 'MARRON', PURPLE: 'PURPURA', PINK: 'ROSA', TURQUOISE: 'TURQUESA',
};

export function normalizeSesVehicleBrand(value?: string | null): string | null {
  if (!value?.trim()) return null;
  const code = BRAND_ALIASES[normalize(value)] || normalize(value);
  return SES_VEHICLE_BRANDS.has(code) ? code : 'OTRO';
}

export function normalizeSesVehicleColor(value?: string | null): string | null {
  if (!value?.trim()) return null;
  const code = COLOR_ALIASES[normalize(value)] || normalize(value);
  return SES_VEHICLE_COLORS.has(code) ? code : 'OTRO';
}
